In [2]:
import pandas as pd

In [3]:
march_clean = pd.read_csv("../data/march_clean.csv")
nov_clean = pd.read_csv("../data/nov_clean.csv")
post_clean = pd.read_csv("../data/post_clean.csv")

In [4]:
df = march_clean.merge(nov_clean, on="QKEY", how="inner")
df.shape
#df.head()

(8148, 13)

In [6]:
march_clean["COVIDCREATE_W63.5"].value_counts()

df["covid_misinfo_belief"] = df["COVIDCREATE_W63.5"].map({"Came about naturally": 0,
                                                          "Was developed intentionally in a lab": 1,
                                                          "Doesn’t really exist": 1})
df["covid_misinfo_belief"].value_counts(dropna=False)

covid_misinfo_belief
0.0    4523
NaN    2136
1.0    1489
Name: count, dtype: int64

In [7]:
pd.crosstab(df["F_PARTYSUM_FINAL"], df["covid_misinfo_belief"], normalize="index")

covid_misinfo_belief       0.0       1.0
F_PARTYSUM_FINAL
DK/Refused/No lean    0.600000  0.400000
Dem/Lean Dem          0.850713  0.149287
Rep/Lean Rep          0.608190  0.391810

In [8]:
df_new = march_clean.merge(post_clean, on="QKEY", how="inner")
df_new.head()

,QKEY,COVIDMISINFO_W63.5,COVIDCREATE_W63.5,F_PARTYSUM_FINAL,F_IDEO,F_AGECAT,F_EDUCCAT,WEIGHT_W63.5,VOTEGEN_POST_W78
0,100197.0,Some,Not sure,Dem/Lean Dem,Moderate,65+,Some College,0.326265,"Joe Biden, the Democrat"
1,100260.0,Some,Was developed intentionally in a lab,Rep/Lean Rep,Very conservative,65+,College graduate+,0.655627,"Donald Trump, the Republican"
2,100314.0,Not much,Was made accidentally in a lab,Rep/Lean Rep,Moderate,65+,Some College,0.432865,"Donald Trump, the Republican"
3,100363.0,None at all,Came about naturally,Dem/Lean Dem,Moderate,30-49,College graduate+,0.396183,"Joe Biden, the Democrat"
4,100446.0,Not much,Not sure,Dem/Lean Dem,Liberal,50-64,College graduate+,0.392344,"Joe Biden, the Democrat"

In [9]:
df_new["covid_misinfo_belief"] = df_new["COVIDCREATE_W63.5"].map({"Came about naturally": 0,
                                                                  "Was developed intentionally in a lab": 1,
                                                                  "Doesn’t really exist": 1})

df_new["trump_vote"] = df_new["VOTEGEN_POST_W78"].map({"Joe Biden, the Democrat": 0,
                                                       "Donald Trump, the Republican": 1})

df_new[["covid_misinfo_belief", "trump_vote"]].dropna().shape

(5079, 2)

In [11]:
df_new.to_csv("../data/merged_clean.csv", index=False)